### ISSUE TITLE
getProperty returns the incorrect height in IE for elements that have padding

### ISSUE THREAD

**Issue by deansimcox** [bigbitecreative/macy.js#13]
It appears that window.getComputedStyle seems to ignore the padding for elements in IE.
I replaced this method call and used offsetHeight instead, and this seem to work.

```
      // tempHeight = parseInt(getProperty(cache.elements[eles[i]], "height").replace("px", ""), 10);
      tempHeight = parseInt(cache.elements[eles[i]].offsetHeight, 10);
```

Cheers
Dean

**Comment by mateuszluczak** [comment]
Hey any update on this issue? Is the library still maintained?
Looks like it's still ocurring

**Comment by deansimcox** [comment]
Haven't heard too much - I probably should have created a pull request though.
Maybe I'll try and do that tomorrow

**Comment by jrmd** [comment]
Hey, 

Apologies on the lack of communication, this was on my list of things to do. I was planning on adding it to the next release when i add variable margins. If you would like to add a pull request then that's fine, I'll check through and merge.

Thanks.

**Comment by jrmd** [comment]
Update,

@deansimcox  I have changed the sort function to now use offsetHeight as per requested. I will update npm to reflect this change soon.

**Comment by deansimcox** [comment]
Top work @jrmd
