### ISSUE TITLE
V1.1.2 is not published on npm

### ISSUE THREAD

**Issue by HelenaWu** [bigbitecreative/macy.js#16]
To start I just want to say thank you for working on macyJS, it's truly an amazing tool and saved a lot of headaches!!
In development I encountered the exact issue ("parent element height set to 0 when some elements are hidden") that was fixed by V1.1.2, however upon updating my npm file and install I received the 'No compatible version found: macy@^1.1.2" error. 

Could you please publish the version to npm? Or is there a temporary code / css fix I can use to bypass the issue?

Many thanks,

**Comment by jrmd** [comment]
Hi @HelenaWu 

Glad you're enjoying Macy, we have pushed 1.1.2 to npm.

Thanks for bringing this to our attention
