### ISSUE TITLE
expand breakAt breakpoints to an object

### ISSUE THREAD

**Issue by teodors** [bigbitecreative/macy.js#17]
I feel that just specifying `breakAt` columns is not enough. Sometimes on smaller screens, you need smaller margins and larger margins in bigger screens.

```
Macy.init({
    container: '#macy-container',
    margin: 24,
    columns: 6,
    breakAt: {
        1200: 5,
        940: 3,
        520: {
                columns: 2,
                margin: 12,
        },
        400: 1
    }
});
```

**Comment by jrmd** [comment]
@teodors currently there is a v2 complete just undergoing testing and should be released soon, I may add this to a 2.1 release as i understand this could be useful
