### ISSUE TITLE
Macy.recalculate() performance degrades quickly as the set gets larger

### ISSUE THREAD

**Issue by chaucerbao** [bigbitecreative/macy.js#2]
I'm really liking the way Macy's looking so far. Simple API, small size.

But I'm running into an issue while creating an infinite-scrolling site. The more I load, the longer `Macy.recalculate()` takes. It actually begins to slow down significantly fairly early, with only a hundred or so items.
1. You may want to consider minimizing layout thrashing with [FastDom](https://github.com/wilsonpage/fastdom) or a similar implementation.
2. Or try to track which items have already been calculated, and skip them. And run a full recalculate on resize.

**Comment by jrmd** [comment]
This should be now resolved in v2
