### ISSUE TITLE
Macy.recalculate

### ISSUE THREAD

**Issue by raedatoui** [bigbitecreative/macy.js#21]
Macy.recalculate seems to be broken using the latest from the master branch
The error that I get: `O.recalculate is not a function`

**Comment by CHEWX** [comment]
Hey,

This has been set-up to use instances, so you need to call the instance. 

I have created a pull request (referenced above) to update the docs.

Thanks,
Tom

**Comment by jrmd** [comment]
Hi @chewx

The instance is automatically created if it isn't called as `new Macy`

@radatoui could you provide me with the code used so I can look in to this. But potentially look at using `var macy_instance = new Macy({ // options })` then doing `macy_instance.recalculate()`

**Comment by raedatoui** [comment]
awesome thank you!

**Comment by raedatoui** [comment]
@jrmd sorry i closed this ticket very quickly
What is currently working for me:
```js
var instance = Macy({
  container: '#'+cards[i].id,
  trueOrder: false,
  waitForImages: false,
  margin: 0,
  columns: 3,
  breakAt: {
    1200: 3,
    978: 2,
    760: 1,
  }
});
instance.recalculate();
```

**Comment by jrmd** [comment]
@raedatoui that code looks correct, is this working?

Thanks,

Jerome

**Comment by raedatoui** [comment]
@jrmd yes, but I do have to call recalculate
