### ISSUE TITLE
version number

### ISSUE THREAD

**Issue by S1SYPHOS** [bigbitecreative/macy.js#25]
Hey there,
just wondering: `package.json` says v2.0.0, Github release history says 1.1.2 ..

**Comment by jrmd** [comment]
Hi @S1SYPHOS I just forgot to release it on github if im honest; this has been resolved :)

**Comment by thedonquixotic** [comment]
@jrmd  Oh does this mean I should redownload the zip and stuff? I had a feeling the dist might be a little behind version wise but wasn't sure.

**Comment by jrmd** [comment]
@thedonquixotic This depends on how you downloaded the zip, did you download it from the releases section or just the download as zip in the `clone or download` section

**Comment by thedonquixotic** [comment]
I downloaded it from the clone and download section, so I'm guessing that
is or was behind versions? This might fix the problem I've been having with
getting recalculate to work.

**Comment by jrmd** [comment]
@thedonquixotic only the releases zip was out of date :)

I do have some README updates to make to reflect the changes to the method names, which i seem to have over looked but did you try my suggestion in #27

**Comment by thedonquixotic** [comment]
Yeah, I'm using that. doesn't seem to be triggering the recalculation, for
some reason :shrug:
