### ISSUE TITLE
[feature] - callback function or events

### ISSUE THREAD

**Issue by CHEWX** [bigbitecreative/macy.js#28]
As per thread title, would be nice to have some events to hook into or a callback function.

**Comment by jrmd** [comment]
@CHEWX this seems like it would be a good idea to add I'll add it on to my list of things to look in to :)

**Comment by jrmd** [comment]
Hey,

In the latest release i have added some events which are documented in the readme. It would be great to get your opinons/suggestions to make macy better :)

**Comment by mytushino** [comment]
Hi - how about the callback function when all the chilren get the style atrribute with left top position values - which would the signal that macy has constructed the grid. 

The emit option is fine but in my case I have EventEmitter.js already in use. 

So something like `done` property in options object would be very handy.

Thanks.
