### ISSUE TITLE
Use Element scope on querySelectorAll

### ISSUE THREAD

**Issue by chaucerbao** [bigbitecreative/macy.js#3]
I noticed your `eles` function using `document.querySelectorAll()`. It might be more appropriate to use  Element.querySelectorAll(). [[MDN]](https://developer.mozilla.org/en-US/docs/Web/API/Element/querySelector).

For example, in your `calculateOnImageLoad()` function, `eles("img")` call will attempt to select all images in the document. My guess is you're really only concerned about the images inside the Macy container, and not other images loading on the site. So use something like `cache.container.querySelectorAll()`.

**Comment by markgoodyear** [comment]
Hey @chaucerbao thanks for the feedback. We're currently looking a v2 release soon which enables multiple Macy's on a page. We will look into this, and #2, to ensure performance doesn't suffer :smile:

**Comment by wjramos** [comment]
I'd love the ability to create a list of nodes outside of Macy and pass in nodes individually, passing configuration through data attributes

**Comment by Pietfro** [comment]
I have created a pull request for that. Feel free to test :)

**Comment by jrmd** [comment]
Hi @Pietfro, I am currently in progress of finalising version 2 of macy which comes with many improvements including element scope, multiple instances and overall performance improvements

**Comment by Pietfro** [comment]
Got it @jrmd . Thanks for the update!
