### ISSUE TITLE
Is breakAt a required property?

### ISSUE THREAD

**Issue by missmatsuko** [bigbitecreative/macy.js#32]
README says that container is the only required property, but the function wouldn't run for me if I didn't have breakAt set.

**Comment by jrmd** [comment]
hey

this should have been fixed in 2.1.1

if not I'll get this fixed and released asap when I release version 2.2

**Comment by jrmd** [comment]
hello,

just a quick update, it turns out this version wasn't published to npm this has since been rectified :)
