### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by fatalmuffin** [bigbitecreative/macy.js#44]
Hi, I couldn't find anything regarding licensing the library.

Is it GNU?

**Comment by jrmd** [comment]
Hi @fatalmuffin 

The script is licensed under MIT which can be seen in the package.json here https://github.com/bigbitecreative/macy.js/blob/master/package.json#L25

Let me know if you have anymore questions,

Thanks,
Jerome

**Comment by MerlinMason** [comment]
Added a PR to make this more clearer :) https://github.com/bigbite/macy.js/pull/58
