### ISSUE TITLE
Breakpoint width measurement off.  Doesnt take scrollbar into account

### ISSUE THREAD

**Issue by adamrobinson** [bigbitecreative/macy.js#46]
It's proving hard to match up the breakpoint values in the plugin with CSS breakpoint values because of the way screen width is calculated. 

Testing In Chrome the breakpoint in the plugin triggers 15px wider than the CSS media query (sizing window up).  15px seems to be the exact size of the scrollbar.

**Comment by jrmd** [comment]
Hey @adamrobinson

Sorry you're having issues with this, I have a fix in mind so I will do some tests and should have fix sorted by tonight

**Comment by jrmd** [comment]
Hey @adamrobinson this issue has been resolved in version 2.3.1 

Let me know if you have any issues with the build.

**Comment by adamrobinson** [comment]
Thank you @jrmd for such a quick fix it’s really appreciated. Will test out the new version first thing in the morning.

**Comment by adamrobinson** [comment]
Works great now. Thanks.
