### ISSUE TITLE
Support for multiple-column spanned tiles

### ISSUE THREAD

**Issue by wjramos** [bigbitecreative/macy.js#6]
I would love to see support for element's widths to be acknowledged and fit appropriately.

![Example](https://www.dropbox.com/s/ob9bnptrewzjp7l/Screenshot%202016-03-30%2016.36.33.png?raw=1)

Several 50% width elements with one 100% width element -- I would expect the full width element to fall on a new line and continue tiling underneath

**Comment by jrmd** [comment]
I created macy to be an extremely lightweight pinterest style masonry layout. I dont feel like I would be able to manage this whilst maintaining the small size and speed.
