### ISSUE TITLE
Multiple Instances per page

### ISSUE THREAD

**Issue by VlooMan** [bigbitecreative/macy.js#7]
Hey, 

Notes say:

> Currently only one instance of macy is supported per page. But that will be subject to change in later versions

Do you have plans on re-working the code to support multiple instances and save all the settings as parameters relative to the current instance only? Any ETA?

Cheers

**Comment by CHEWX** [comment]
You can do multiply instances by using unique `container`.

There is a caveat on this, so depends your use. On resize, it will only attach the the last instance, the same goes for any methods.

**Comment by jrmd** [comment]
@VlooMan When i release v2, which should be shortly, this will be addressed

**Comment by raedatoui** [comment]
@jrmd  any progress ?

**Comment by jrmd** [comment]
@raedatoui V2 is now live on this repo, with multiple instance support, but needs pushing to npm.

**Comment by raedatoui** [comment]
cool, thank you!! 
`recalculate`  seems to be broken: `O.recalculate is not a function`

**Comment by CHEWX** [comment]
@raedatoui I would raise a new issue, this can be closed now.

**Comment by raedatoui** [comment]
@CHEWX sounds good. opened #21
