### ISSUE TITLE
Is it possible to center Macy items?

### ISSUE THREAD

**Issue by crn1** [bigbitecreative/macy.js#74]
Is it possible to center Macy items in a container? Like `justify-content` for flexbox, just for Macy?

**Comment by crn1** [comment]
Closing because I just now realized that this is a stupid question.

**Comment by frontedbe** [comment]
@crn1 I'm probably missing something here but may I ask how you solved this? I have my container items flexed and justify-centered but they still get aligned to the left...

**Comment by crn1** [comment]
> @crn1 I'm probably missing something here but may I ask how you solved this? I have my container items flexed and justify-centered but they still get aligned to the left...

Sorry, I was using Macy a long time ago and now I don't really remember how I solved it. I think it couldn't be done because of the nature of Macy. It "physically" wasn't possible I think. Or I used simple CSS, I can't recall.
