### ISSUE TITLE
SOLVED: Display issue on Safari and Samsung browser (with Cloudinary and a lot of images)

### ISSUE THREAD

**Issue by marcfilleul** [bigbitecreative/macy.js#78]
Hi,

I'm using Macy with multiple galleries on [this page](https://oliviapoumeyrol.netlify.app/galerie/).

It works well on my PC and Android phone but it doesn't work on my 2 iPad (Safari, Chrome and Firefox).

The page takes longer to load on my iPad, then it loads about 25% of my images only and the layout is broken.
It also freezes the browser if I scroll down then up.

I really don't know what happens but it looks like a performance issue.

Here is again the link to the page : [gallery issue page](https://oliviapoumeyrol.netlify.app/galerie/)

If somebody can help me figure this out, it would be great!

Thanks in advance.

**Comment by marcfilleul** [comment]
Two hours ago, my client told me about a similar issue on 4 different mobile phones.

She described the same display bug without knowing about the iPad issue I had, so I suppose it's a performance issue as I have no trouble in my high-end mobile.

Is there a way to solve this?

**Comment by marcfilleul** [comment]
Finally, it's not a performance issue because my client have the issue on high-end mobile phones.

After several tests, the issue happens on Samsung browser and on Apple mobile devices, so it looks like a browser compatibility issue.

Any clue?

**Comment by marcfilleul** [comment]
After several tests, and without understanding why, I found the culprit.
Cloudinary was causing the issue on some browsers only.

When using locally hosted images, everything works just fine!

**Comment by bojanvidanovic** [comment]
> After several tests, and without understanding why, I found the culprit.
> Cloudinary was causing the issue on some browsers only.
> 
> When using locally hosted images, everything works just fine!

I experienced the same issue yesterday, I found a quick fix by setting waitForImages to true.
